[package]
name = "gemini-commit-message"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
ureq = {version = "3.2.0", features = ["json"]}
